# Generated by Django 6.1.1 on 2026-09-04 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('global_code', models.CharField(max_length=150, unique=True)),
                ('parameter_name', models.CharField(max_length=255)),
                ('parameter_description', models.TextField(blank=True, null=True)),
                ('uom', models.CharField(blank=True, max_length=50, null=True)),
                ('minvalue', models.FloatField(blank=True, null=True)),
                ('maxvalue', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plant_code', models.CharField(max_length=100, unique=True)),
                ('plant_name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dashboard_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('definition', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='core.plant')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterValue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.parameter')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_values', to='core.plant')),
            ],
            options={
                'indexes': [models.Index(fields=['parameter', '-timestamp'], name='core_parame_paramet_9b7b2a_idx'), models.Index(fields=['plant', '-timestamp'], name='core_parame_plant_i_fe7ae0_idx')],
            },
        ),
    ]
