# Generated by Django 6.1.1 on 2026-09-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='parametervalue',
            name='core_parame_plant_i_fe7ae0_idx',
        ),
        migrations.AddIndex(
            model_name='parametervalue',
            index=models.Index(fields=['plant', 'parameter', '-timestamp'], name='core_parame_plant_i_ca1b01_idx'),
        ),
        migrations.AddConstraint(
            model_name='parametervalue',
            constraint=models.UniqueConstraint(fields=('plant', 'parameter', 'timestamp'), name='unique_plant_parameter_timestamp'),
        ),
    ]
