# Generated by Django 6.1.1 on 2026-09-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_parametervalue_core_parame_plant_i_fe7ae0_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterMetaData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('global_code', models.CharField(max_length=150, unique=True)),
                ('parameter_name', models.CharField(max_length=255)),
                ('parameter_description', models.TextField(blank=True, null=True)),
                ('uom', models.CharField(blank=True, max_length=50, null=True)),
                ('minvalue', models.FloatField(blank=True, null=True)),
                ('maxvalue', models.FloatField(blank=True, null=True)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('process', models.CharField(blank=True, max_length=100, null=True)),
                ('asset', models.CharField(blank=True, max_length=100, null=True)),
                ('metric_type', models.CharField(blank=True, max_length=100, null=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
