# Generated by Django 6.1.1 on 2026-09-15 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_parametermetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametervalue',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.parametermetadata'),
        ),
    ]
