import json
import re


def parse_json_response(text):

    if not text:
        raise ValueError(
            "AI returned an empty response."
        )

    print(f"\n{'=' * 80}\n ========== RAW QWEN RESPONSE ==========\n")
    print(text)
    print(f"\n{'=' * 80}\n ========== END RAW QWEN RESPONSE ==========\n")

    text = text.strip()

    # Remove markdown code fences
    text = re.sub(
        r"^```json\s*",
        "",
        text,
        flags=re.IGNORECASE,
    )

    text = re.sub(
        r"^```\s*",
        "",
        text,
    )

    text = re.sub(
        r"\s*```$",
        "",
        text,
    )

    text = text.strip()

    start = text.find("{")
    end = text.rfind("}")

    if start == -1 or end == -1:

        raise ValueError(
            "AI response does not contain a JSON object."
        )

    json_text = text[start:end + 1]

    try:

        return json.loads(json_text)

    except json.JSONDecodeError as exc:

        print(f"\n{'=' * 80}\n========== JSON PARSE ERROR ==========\n{'=' * 80}\n")
        
        print(
            f"Error: {exc}"
        )

        print(
            f"Line: {exc.lineno}"
        )

        print(
            f"Column: {exc.colno}"
        )

        print(
            f"Character: {exc.pos}"
        )

        print("=" * 80)

        # Show the area around the error
        lines = json_text.splitlines()

        start_line = max(
            0,
            exc.lineno - 5
        )

        end_line = min(
            len(lines),
            exc.lineno + 5
        )

        print(
            "\n========== JSON AROUND ERROR =========="
        )

        for index in range(
            start_line,
            end_line
        ):

            marker = " >>> " if (
                index + 1 == exc.lineno
            ) else "     "

            print(
                f"{marker}{index + 1}: "
                f"{lines[index]}"
            )

        print(
            "========================================"
        )

        raise ValueError(
            f"Invalid JSON generated by Qwen: {exc}"
        )


# import json
# import re


# def parse_json_response(text):

#     if not text:
#         raise ValueError(
#             "AI returned an empty response."
#         )

#     text = text.strip()

#     text = re.sub(
#         r"^```json",
#         "",
#         text,
#         flags=re.IGNORECASE,
#     )

#     text = re.sub(
#         r"^```",
#         "",
#         text
#     )

#     text = re.sub(
#         r"```$",
#         "",
#         text
#     )

#     text = text.strip()

#     start = text.find("{")
#     end = text.rfind("}")

#     if start == -1 or end == -1:
#         raise ValueError(
#             "AI response does not contain JSON."
#         )

#     return json.loads(
#         text[start:end + 1]
#     )




# import json
# import re


# def parse_json_response(answer):

#     if not answer:
#         raise ValueError(
#             "AI returned an empty response."
#         )

#     answer = answer.strip()

#     answer = re.sub(
#         r"```json",
#         "",
#         answer,
#         flags=re.IGNORECASE
#     )

#     answer = answer.replace(
#         "```",
#         ""
#     ).strip()

#     start = answer.find("{")
#     end = answer.rfind("}")

#     if start == -1 or end == -1:
#         raise ValueError(
#             "No JSON object found."
#         )

#     json_text = answer[
#         start:end + 1
#     ]

#     try:
#         return json.loads(json_text)

#     except json.JSONDecodeError as error:
#         raise ValueError(
#             f"Invalid JSON: {error}"
#         )